# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.ciao.ink
date_format: "ordinal"
title: 所以ciao
subtitle: "生活是苦难的，我又划着我的断桨出发了。"
description: "个人博客"
keywords: 所以ciao,blog
favicon: /assets/images/favicon.ico
timezone: Beijing
encoding: "UTF-8"
source_code: https://www.ciao.ink

# ---------------- #
#      Author      #
# ---------------- #
author: Bing xu
organization: Hust
#organization_url: https://www.hust.edu.cn
location: Wuhan, China
email: imxubing@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 博客主页

  -
    href: /categories/
    label: 文章分类

  -
    href: /expend/
    label: 扩充页面

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS:null   #
# ---------------- #
subscribe_rss: null #/feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: xnzaa
QQ: 649981201
Email: 649981201@qq.com

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan

# !!!Important!!! Please modify usernames below to yours
#多说评论服务供应商
comments_provider: 
duoshuo_username: 
#百度统计
baidu_statistics: 
# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, Java]
skill_mobile_app_keywords: ["NULL"]
skill_windows_keywords: ["NULL"]
#popular_repos: ['chinese-copywriting-guidelines','android-reverse-engineering', 'csdncommenter', 'mzlogin.github.io', 'vim-markdown-toc']
#contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']
